import { search } from "../scripts/active_listing_search.js";
import { closeConnection } from "../scripts/mysql_conn.js";
const userId = "1234";
const json = { "city": "Irvine", "maxPrice": 1500000, "beds": 3, "baths": null, "sqft": null, "type": "Condominium", "pool": null, "hasView": null, "maxhoaPrice": null };
const hyphenLine = "-".repeat(40);
const searchResults = await search(userId, json, 1, 10);
console.log(searchResults);
console.log(hyphenLine);
const searchResultsPage = await search(userId, json, 2, 10);
console.log(searchResultsPage);
console.log(hyphenLine);
const searchResultsLimit = await search(userId, json, 1, 20);
console.log(searchResultsLimit);
console.log(hyphenLine);
const searchResultsBothPageLimit = await search(userId, json, 2, 20);
console.log(searchResultsBothPageLimit);
console.log(hyphenLine);
const searchResultsMissingId = await search("", json, 1, 10);
console.log(searchResultsMissingId);
console.log(hyphenLine);
const userId_2 = "234";
const json_city = { "city": null, "maxPrice": null, "beds": null, "baths": null, "sqft": null, "type": null, "pool": null, "hasView": null, "maxhoaPrice": null };
const searchResultsMissingCity = await search(userId_2, json_city, 1, 10);
console.log(searchResultsMissingCity);
console.log(hyphenLine);
const json_price = { "city": "Irvine", "maxPrice": null, "beds": null, "baths": null, "sqft": null, "type": null, "pool": null, "hasView": null, "maxhoaPrice": null };
const searchResultsMissingPrice = await search(userId_2, json_price, 1, 10);
console.log(searchResultsMissingPrice);
console.log(hyphenLine);
const json_beds = { "city": "Irvine", "maxPrice": 1500000, "beds": null, "baths": null, "sqft": null, "type": null, "pool": null, "hasView": null, "maxhoaPrice": null };
const searchResultsMissingBeds = await search(userId_2, json_beds, 1, 10);
console.log(searchResultsMissingBeds);
console.log(hyphenLine);
const json_type = { "city": "Irvine", "maxPrice": 1500000, "beds": 3, "baths": null, "sqft": null, "type": null, "pool": null, "hasView": null, "maxhoaPrice": null };
const searchResultsMissingType = await search(userId_2, json_type, 1, 10);
console.log(searchResultsMissingType);
console.log(hyphenLine);
await closeConnection();
